Workaround for error in rspec-parameterized-table_syntax
```
An error occurred while loading ./spec/ruby_h_to_go/function_definition_spec.rb.
Failure/Error: "RB_FIX2INT" | "RB_FIX2INT"

NoMethodError:
  undefined method 'of_caller' for an instance of Binding
 # /home/runner/work/go-gem-wrapper/go-gem-wrapper/vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-table_syntax-2.0.1/lib/rspec/parameterized/table_syntax/table_syntax_implement.rb:6:in '|'
 # ./spec/ruby_h_to_go/function_definition_spec.rb:542:in 'block (3 levels) in <top (required)>'
 # /home/runner/work/go-gem-wrapper/go-gem-wrapper/vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'BasicObject#instance_eval'
 # /home/runner/work/go-gem-wrapper/go-gem-wrapper/vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'RSpec::Parameterized::Core::ExampleGroupMethods#define_cases'
 # /home/runner/work/go-gem-wrapper/go-gem-wrapper/vendor/bundle/ruby/4.0.0+0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:84:in 'RSpec::Parameterized::Core::ExampleGroupMethods#with_them'
 # ./spec/ruby_h_to_go/function_definition_spec.rb:546:in 'block (2 levels) in <top (required)>'
 # ./spec/ruby_h_to_go/function_definition_spec.rb:527:in 'block in <top (required)>'
 # ./spec/ruby_h_to_go/function_definition_spec.rb:3:in '<top (required)>'
```